#!/usr/bin/env node

/**
 * Initialize GraphQL Directory Structure
 * 
 * Creates the necessary directory structure for GraphQL operations
 * if it doesn't already exist.
 */

const fs = require('fs');
const path = require('path');

const GRAPHQL_DIR = path.join(__dirname, '../lib/graphql');

console.log('📁 Initializing GraphQL directory structure...');

// Create lib/graphql directory if it doesn't exist
if (!fs.existsSync(GRAPHQL_DIR)) {
  fs.mkdirSync(GRAPHQL_DIR, { recursive: true });
  console.log('✅ Created lib/graphql directory');
} else {
  console.log('✅ lib/graphql directory already exists');
}

// Create placeholder files if they don't exist
const files = [
  {
    name: 'queries.ts',
    content: `/* tslint:disable */
/* eslint-disable */
// This file will be auto-generated by Amplify codegen
// Run: npm run schema:generate

export {};
`
  },
  {
    name: 'mutations.ts',
    content: `/* tslint:disable */
/* eslint-disable */
// This file will be auto-generated by Amplify codegen
// Run: npm run schema:generate

export {};
`
  },
  {
    name: 'subscriptions.ts',
    content: `/* tslint:disable */
/* eslint-disable */
// This file will be auto-generated by Amplify codegen
// Run: npm run schema:generate

export {};
`
  }
];

files.forEach(({ name, content }) => {
  const filePath = path.join(GRAPHQL_DIR, name);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content);
    console.log(`✅ Created ${name}`);
  } else {
    console.log(`✅ ${name} already exists`);
  }
});

console.log('🎉 GraphQL directory structure initialized!');
console.log('');
console.log('Next steps:');
console.log('1. Run: npm run schema:download (to download schema from AppSync)');
console.log('2. Run: npm run schema:generate (to generate TypeScript types)');
